// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aoeplkarjhlyucppawxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZXBsa2FyamhseXVjcHBhd3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTczODMsImV4cCI6MjA2MTI3MzM4M30.ZcvoxYjypuQYKSqkHozTUR2XQW71DLN2TAqBufeIqII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);